'use client';

import React, { useRef } from 'react';

function PrintaddBill() {
  const formRef = useRef(null);
  const isMobile = /Mobi|Android/i.test(
    typeof navigator !== 'undefined' ? navigator.userAgent : ''
  );

  const handlePrint = async () => {
    if (!formRef.current) return;

    const formData = new FormData(formRef.current);

    const data = {
      Date: formData.get('date'),
      Vessel: formData.get('vessel'),
      Terminal: formData.get('terminal'),
      'L.C No': formData.get('lcNo'),
      Index: formData.get('index'),
      Product: formData.get('product'),
      'Cash No': formData.get('cashNo'),
      'Serial No': formData.get('serialNo'),
      'Phone No': formData.get('phoneNo'),
      Weight: formData.get('weight'),
      Mobile: formData.get('mobile'),
      'Total Freight': formData.get('totalFreight'),
      'Bilty No': formData.get('biltyNo'),
    };

    const htmlContent = `
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
              color: #333;
              background: #f8fafc;
            }
            h1 {
              text-align: center;
              color: #4f46e5;
              margin-bottom: 30px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 40px;
            }
            th, td {
              padding: 12px 15px;
              border: 1px solid #ddd;
            }
            th {
              background-color: #4f46e5;
              color: white;
              text-align: left;
            }
            tr:nth-child(even) {
              background-color: #e0e7ff;
            }
            .footer {
              text-align: center;
              font-size: 0.9rem;
              color: #666;
              border-top: 1px solid #ccc;
              padding-top: 10px;
            }
          </style>
        </head>
        <body>
          <h1>Shipping Document</h1>
          <table>
            <tbody>
              ${Object.entries(data)
                .map(
                  ([key, value]) => `
                    <tr>
                      <th>${key}</th>
                      <td>${value || '-'}</td>
                    </tr>
                  `
                )
                .join('')}
            </tbody>
          </table>
          <div class="footer">Generated by Shipping App</div>
        </body>
      </html>
    `;

    if (isMobile) {
      const element = document.createElement('div');
      element.innerHTML = htmlContent;

      // Dynamically import html2pdf on the client only
      const html2pdf = (await import('html2pdf.js')).default;

      html2pdf()
        .from(element)
        .set({
          margin: 10,
          filename: 'shipping-document.pdf',
          html2canvas: { scale: 2 },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        })
        .save();
    } else {
      const printWindow = window.open('', '', 'width=800,height=600');
      if (!printWindow) return alert('Pop-up blocked, please allow pop-ups.');

      printWindow.document.write(htmlContent);
      printWindow.document.write(`
        <script>
          window.onload = function() {
            window.print();
            window.onafterprint = function() {
              window.close();
            }
          }
        </script>
      `);
      printWindow.document.close();
    }
  };

  return (
    <div className="bg-gray-100 flex items-center justify-center min-h-screen p-4">
      <form
        ref={formRef}
        className="bg-white shadow-md rounded px-4 py-6 sm:px-8 sm:py-8 w-full max-w-3xl box-border"
        onSubmit={(e) => {
          e.preventDefault();
          alert('Form submitted!');
        }}
      >
        <h2 className="text-2xl font-bold mb-8 text-center">Shipping Form</h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {[
            { id: 'date', label: 'Date', type: 'date' },
            { id: 'vessel', label: 'Vessel', type: 'text', placeholder: 'Enter vessel name' },
            { id: 'terminal', label: 'Terminal', type: 'text', placeholder: 'Enter terminal' },
            { id: 'lcNo', label: 'L.C No', type: 'text', placeholder: 'Enter L.C number' },
            { id: 'index', label: 'Index', type: 'text', placeholder: 'Enter index' },
            { id: 'product', label: 'Product', type: 'text', placeholder: 'Enter product' },
            { id: 'cashNo', label: 'Cash No', type: 'text', placeholder: 'Enter cash number' },
            { id: 'serialNo', label: 'Serial No', type: 'text', placeholder: 'Enter serial number' },
            { id: 'phoneNo', label: 'Phone No', type: 'tel', placeholder: '+1-234-567-8900' },
            { id: 'weight', label: 'Weight (kg)', type: 'number', placeholder: 'Enter weight' },
            { id: 'mobile', label: 'Mobile', type: 'tel', placeholder: '+1-234-567-8900' },
            { id: 'totalFreight', label: 'Total Freight ($)', type: 'number', placeholder: 'Enter total freight' },
            { id: 'biltyNo', label: 'Bilty No', type: 'text', placeholder: 'Enter bilty number' },
          ].map(({ id, label, type, placeholder }) => (
            <label htmlFor={id} className="block" key={id}>
              <span className="text-gray-700 font-semibold mb-2 block">{label}</span>
              <input
                type={type}
                id={id}
                name={id}
                required
                placeholder={placeholder}
                className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </label>
          ))}
        </div>

        <div className="mt-8 flex justify-center space-x-4">
          <button
            type="submit"
            className="bg-indigo-600 text-white font-semibold px-6 py-3 rounded-md hover:bg-indigo-700 transition"
          >
            Submit
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="bg-green-600 text-white font-semibold px-6 py-3 rounded-md hover:bg-green-700 transition"
          >
            {isMobile ? 'Download PDF' : 'Print'}
          </button>
        </div>
      </form>
    </div>
  );
}

export default PrintaddBill;
