'use client'
import React, { useRef } from "react";

function PrintaddBill() {
  const formRef = useRef(null);

  const handlePrint = () => {
    if (!formRef.current) return;

    const formData = new FormData(formRef.current);

    const data = {
      Date: formData.get("date"),
      Vessel: formData.get("vessel"),
      Terminal: formData.get("terminal"),
      "L.C No": formData.get("lcNo"),
      Index: formData.get("index"),
      Product: formData.get("product"),
      "Cash No": formData.get("cashNo"),
      "Serial No": formData.get("serialNo"),
      "Phone No": formData.get("phoneNo"),
      Weight: formData.get("weight"),
      Mobile: formData.get("mobile"),
      "Total Freight": formData.get("totalFreight"),
      "Bilty No": formData.get("biltyNo"),
    };

    const printWindow = window.open("", "", "width=800,height=600");
    if (!printWindow) return alert("Pop-up blocked, please allow pop-ups.");

    printWindow.document.write(`
      <html>
        <head>
          <title>Print Shipping Data</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
              color: #333;
              background: #f8fafc;
            }
            h1 {
              text-align: center;
              color: #4f46e5;
              margin-bottom: 30px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 40px;
            }
            th, td {
              padding: 12px 15px;
              border: 1px solid #ddd;
            }
            th {
              background-color: #4f46e5;
              color: white;
              text-align: left;
            }
            tr:nth-child(even) {
              background-color: #e0e7ff;
            }
            .footer {
              text-align: center;
              font-size: 0.9rem;
              color: #666;
              border-top: 1px solid #ccc;
              padding-top: 10px;
            }
          </style>
        </head>
        <body>
          <h1>Shipping Document</h1>
          <table>
            <tbody>
              ${Object.entries(data)
                .map(
                  ([key, value]) => `
                <tr>
                  <th>${key}</th>
                  <td>${value || "-"}</td>
                </tr>
              `
                )
                .join("")}
            </tbody>
          </table>
          <div class="footer">Generated by Shipping App</div>
          <script>
            window.onload = function() {
              window.print();
              window.onafterprint = function() {
                window.close();
              }
            }
          </script>
        </body>
      </html>
    `);

    printWindow.document.close();
  };

  return (
    <div className="bg-gray-100 flex items-center justify-center min-h-screen p-4">
      <form
        ref={formRef}
        className="bg-white shadow-md rounded px-4 py-6 sm:px-8 sm:py-8 w-full max-w-3xl box-border"
        onSubmit={(e) => {
          e.preventDefault();
          alert("Form submitted!");
        }}
      >
        <h2 className="text-2xl font-bold mb-8 text-center">Shipping Form</h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {/* Date */}
          <label htmlFor="date" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Date</span>
            <input
              type="date"
              id="date"
              name="date"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Vessel */}
          <label htmlFor="vessel" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Vessel</span>
            <input
              type="text"
              id="vessel"
              name="vessel"
              placeholder="Enter vessel name"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Terminal */}
          <label htmlFor="terminal" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Terminal</span>
            <input
              type="text"
              id="terminal"
              name="terminal"
              placeholder="Enter terminal"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* L.C No */}
          <label htmlFor="lcNo" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">L.C No</span>
            <input
              type="text"
              id="lcNo"
              name="lcNo"
              placeholder="Enter L.C number"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Index */}
          <label htmlFor="index" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Index</span>
            <input
              type="text"
              id="index"
              name="index"
              placeholder="Enter index"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Product */}
          <label htmlFor="product" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Product</span>
            <input
              type="text"
              id="product"
              name="product"
              placeholder="Enter product"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Cash No */}
          <label htmlFor="cashNo" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Cash No</span>
            <input
              type="text"
              id="cashNo"
              name="cashNo"
              placeholder="Enter cash number"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Serial No */}
          <label htmlFor="serialNo" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Serial No</span>
            <input
              type="text"
              id="serialNo"
              name="serialNo"
              placeholder="Enter serial number"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Phone No */}
          <label htmlFor="phoneNo" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Phone No</span>
            <input
              type="tel"
              id="phoneNo"
              name="phoneNo"
              placeholder="+1-234-567-8900"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Weight */}
          <label htmlFor="weight" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">
              Weight (kg)
            </span>
            <input
              type="number"
              id="weight"
              name="weight"
              placeholder="Enter weight"
              min="0"
              step="0.01"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Mobile */}
          <label htmlFor="mobile" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Mobile</span>
            <input
              type="tel"
              id="mobile"
              name="mobile"
              placeholder="+1-234-567-8900"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Total Freight */}
          <label htmlFor="totalFreight" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">
              Total Freight ($)
            </span>
            <input
              type="number"
              id="totalFreight"
              name="totalFreight"
              placeholder="Enter total freight"
              min="0"
              step="0.01"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          {/* Bilty No */}
          <label htmlFor="biltyNo" className="block">
            <span className="text-gray-700 font-semibold mb-2 block">Bilty No</span>
            <input
              type="text"
              id="biltyNo"
              name="biltyNo"
              placeholder="Enter bilty number"
              required
              className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
        </div>

        <div className="mt-8 flex justify-center space-x-4">
          <button
            type="submit"
            className="bg-indigo-600 text-white font-semibold px-6 py-3 rounded-md hover:bg-indigo-700 transition"
          >
            Submit
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="bg-green-600 text-white font-semibold px-6 py-3 rounded-md hover:bg-green-700 transition"
          >
            Print
          </button>
        </div>
      </form>
    </div>
  );
}

export default PrintaddBill;
